name = "nix-cache"
main = "src/index.ts"
compatibility_date = "2022-05-18"
account_id = "1c495e64ff5fd527342d7b7bf6731a1f"
route = "nix-cache.piperswe.me/*"

[vars]
CACHE_CONTROL = "max-age=86400"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "nix-cache"
preview_bucket_name = "nix-cache"
